# Site settings
title: Remote Work The Right Way
description: Have you ever heard about “Remote work”? There are a lot of resources regarding this topic analyzing it
 from several perspectives. We want to sum up all the best practices of this way of working picking the best
 resources on the web.
baseurl: ""
url: "http://www.remoteworktherightway.com"

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false

exclude: ['CNAME', 'LICENSE', 'README.md']
